# Generated by Django 4.1 on 2022-08-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uername',
            new_name='username',
        ),
    ]
