# Generated by Django 4.1 on 2022-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_uername_transaction_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(blank=True, choices=[('Housing', 'Housing'), ('School', 'School'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Medical', 'Medical'), ('Saving', 'Saving')], max_length=30),
        ),
    ]
