# Generated by Django 4.1 on 2022-08-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='Id',
        ),
    ]
