# Generated by Django 4.1 on 2022-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=None, upload_to='', verbose_name='photos/%y/%m/%d'),
        ),
    ]
