# Generated by Django 4.1 on 2022-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_user_balance_user_expense_user_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('Type', models.CharField(max_length=7)),
                ('amount', models.FloatField(default=0)),
                ('Category', models.CharField(choices=[('Housing', 'Housing'), ('School', 'School'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Medical', 'Medical'), ('Saving', 'Saving')], max_length=30)),
                ('uername', models.CharField(max_length=20)),
            ],
        ),
    ]
