# Generated by Django 4.1 on 2022-08-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
