# Generated by Django 4.1 on 2022-08-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=None, upload_to='photos/%y/%m/%d'),
        ),
    ]
