# Generated by Django 4.1 on 2022-08-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='expense',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=None, upload_to='profiles'),
        ),
    ]
