# Generated by Django 4.1 on 2022-08-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profiles/robot.png', upload_to='profiles'),
        ),
    ]
